### ISSUE TITLE
support username / password

### ISSUE THREAD

**Issue by flyerhzm** [a2800276/http-parser.java#5]
If url contains username and password, like

```
http://user:passwd@example.com
```

it will raise exception, saying "invalid port", do you have any idea how to fix it?

**Comment by a2800276** [comment]
I don't believe this should affect the http parser. Shouldn't the user/passwd part of the URI be translated to an approriate authorization mechanism -> probably http basic? I'm fairly certain the authorization bits before the @ ever hit the server, but I'll check. Or am I misunderstanding your question? Could you point me to the part of the JRuby API you are refering to?

**Comment by flyerhzm** [comment]
you are right, I have tested it, user/password part won't hit server, thank you for pointing it out.
